"use strict";(()=>{var e={};e.id=6707,e.ids=[6707],e.modules={3295:e=>{e.exports=require("next/dist/server/app-render/after-task-async-storage.external.js")},10846:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},19771:e=>{e.exports=require("process")},21572:e=>{e.exports=require("nodemailer")},27910:e=>{e.exports=require("stream")},28354:e=>{e.exports=require("util")},29294:e=>{e.exports=require("next/dist/server/app-render/work-async-storage.external.js")},30483:(e,s,t)=>{t.r(s),t.d(s,{patchFetch:()=>b,routeModule:()=>c,serverHooks:()=>_,workAsyncStorage:()=>d,workUnitAsyncStorage:()=>m});var a={};t.r(a),t.d(a,{POST:()=>p});var i=t(96559),r=t(48088),n=t(37719),o=t(32190),l=t(5069);let{sendBusinessVerificationEmail:u}=t(20048);async function p(e){let s=new URL(e.url).pathname.split("/"),t=s[s.length-2];try{let s,a,i,r=parseInt(t);if(isNaN(r))return o.NextResponse.json({message:"Invalid business ID"},{status:400});let{note:n,requestDocuments:p}=await e.json();if(!n||n.trim().length<10)return o.NextResponse.json({message:"Please provide a detailed reason for declining (minimum 10 characters)"},{status:400});let c="declined",d=(await (0,l.query)(`
      SELECT table_name
      FROM information_schema.tables
      WHERE table_schema = DATABASE()
      AND table_name IN ('business_profiles', 'service_providers')
    `)).map(e=>e.table_name);console.log("Available tables:",d);let m=d.includes("service_providers"),_=d.includes("business_profiles");if(!m&&!_)return console.error("Neither business_profiles nor service_providers table exists in the database"),o.NextResponse.json({message:"Database schema error: Required tables do not exist"},{status:500});let b=m?"service_providers":"business_profiles";console.log(`Using table: ${b}`);let f=(await (0,l.query)(`
      SHOW COLUMNS FROM ${b} LIKE 'application_status'
    `)).length>0;if(console.log(`Table ${b} has application_status column: ${f}`),s=await (0,l.query)(`UPDATE ${b}
       SET application_status = ?,
           verification_notes = ?,
           verification_date = NOW(),
           updated_at = NOW()
       WHERE id = ?`,[c,n.trim(),r]),console.log(`Updated ${b} with ID ${r} to application_status: ${c}`),console.log("Update result:",s),0===s.affectedRows)return o.NextResponse.json({message:"Business profile not found"},{status:404});if(await (0,l.query)("COMMIT"),console.log("Committed transaction for status update"),f){if((a=await (0,l.query)(`SELECT application_status FROM ${b} WHERE id = ?`,[r]))&&a.length>0){let e=a[0];console.log(`Verified status for ${b} with ID ${r}: application_status=${e.application_status}`),e.application_status!==c&&(console.error(`Status mismatch! Expected application_status=${c}, but got application_status=${e.application_status}`),await (0,l.query)(`UPDATE ${b} SET application_status = ? WHERE id = ?`,[c,r]),await (0,l.query)("COMMIT"))}}else{console.log("Warning: The table does not have application_status column, but should have been migrated");try{await (0,l.query)(`ALTER TABLE ${b} ADD COLUMN application_status ENUM('pending', 'approved', 'declined', 'restricted') DEFAULT 'pending'`),console.log(`Added application_status column to ${b} table`),await (0,l.query)(`UPDATE ${b} SET application_status = ? WHERE id = ?`,[c,r]),console.log(`Updated the new application_status column for business ID ${r}`),await (0,l.query)("COMMIT")}catch(e){console.error("Error adding application_status column:",e)}}let g=(m?await (0,l.query)(`SELECT
          bp.*,
          u.email,
          u.first_name,
          u.last_name,
          bp.name as business_name
         FROM service_providers bp
         JOIN users u ON bp.user_id = u.id
         WHERE bp.id = ?`,[r]):await (0,l.query)(`SELECT bp.*, u.email, u.first_name, u.last_name
         FROM business_profiles bp
         JOIN users u ON bp.user_id = u.id
         WHERE bp.id = ?`,[r]))[0],E=!1;if(g){try{console.log(`Preparing to send notification email to ${g.email} for business ${g.business_name||g.name}`);let e=await u(g.email,{businessName:g.business_name||g.name,contactName:`${g.first_name} ${g.last_name}`,status:p?"documents_required":"declined",notes:n.trim()});e.success?(console.log(`Notification email sent successfully to ${g.email}. Message ID: ${e.messageId}`),E=!0):console.error("Failed to send notification email:",e.error)}catch(e){console.error("Failed to send notification email:",e)}try{let e=await (0,l.query)(`
          SELECT COUNT(*) as count
          FROM information_schema.tables
          WHERE table_schema = ? AND table_name = 'notifications'
        `,["rainbow_paws"]);e&&Array.isArray(e)&&e[0]&&e[0].count>0&&await (0,l.query)(`
            INSERT INTO notifications (user_id, title, message, type, link, is_read)
            VALUES (?, ?, ?, ?, ?, ?)
          `,[g.user_id,p?"Additional Documents Required":"Application Declined",p?`Your business application for ${g.business_name||g.name} requires additional documents. Please check your email for details.`:`Your business application for ${g.business_name||g.name} has been declined. Reason: ${n.trim().substring(0,100)}${n.trim().length>100?"...":""}`,p?"warning":"error","/business/profile",0])}catch(e){console.error("Failed to create notification:",e)}}return await (0,l.query)(`INSERT INTO admin_logs (action, entity_type, entity_id, details, admin_id)
       VALUES (?, ?, ?, ?, ?)`,[p?"request_documents":"decline_business",b,r,JSON.stringify({businessName:g?.business_name||g?.name,notes:n.trim(),requestDocuments:!!p}),1]).catch(e=>console.error("Failed to log admin action:",e)),o.NextResponse.json({message:p?"Documents requested successfully":"Application declined successfully",businessId:r,businessName:g?.business_name||g?.name,status:c,emailSent:E})}catch(e){return console.error("Error processing application:",e),o.NextResponse.json({message:"Failed to process application"},{status:500})}}let c=new i.AppRouteRouteModule({definition:{kind:r.RouteKind.APP_ROUTE,page:"/api/businesses/applications/[id]/decline/route",pathname:"/api/businesses/applications/[id]/decline",filename:"route",bundlePath:"app/api/businesses/applications/[id]/decline/route"},resolvedPagePath:"C:\\xampp\\htdocs\\app_rainbowpaws\\src\\app\\api\\businesses\\applications\\[id]\\decline\\route.ts",nextConfigOutput:"standalone",userland:a}),{workAsyncStorage:d,workUnitAsyncStorage:m,serverHooks:_}=c;function b(){return(0,n.patchFetch)({workAsyncStorage:d,workUnitAsyncStorage:m})}},34631:e=>{e.exports=require("tls")},41204:e=>{e.exports=require("string_decoder")},44870:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},55511:e=>{e.exports=require("crypto")},63033:e=>{e.exports=require("next/dist/server/app-render/work-unit-async-storage.external.js")},66136:e=>{e.exports=require("timers")},74075:e=>{e.exports=require("zlib")},79428:e=>{e.exports=require("buffer")},79551:e=>{e.exports=require("url")},91645:e=>{e.exports=require("net")},94735:e=>{e.exports=require("events")}};var s=require("../../../../../../webpack-runtime.js");s.C(e);var t=e=>s(s.s=e),a=s.X(0,[4447,580,6101,9570],()=>t(30483));module.exports=a})();